### ISSUE TITLE
Нет модуля requests

### ISSUE THREAD

**Issue by waryak** [yandexdataschool/neurohack-2016-starterkit#1]
Когда лаунчишь тетрадку contest_submission на эверваре, он говорит, что нет модуля requests, хотя модуль есть;(

**Comment by astiunov** [comment]
Спасибо за тикет, минут через 20-30 образ обновится и мы напишем, как в everware перезапустить

**Comment by astiunov** [comment]
Пока же можете сделать в терминале следующее:
```
source activate py3_env && conda install -y requests
```

Ну либо py2, смотря какой питон используете

**Comment by astiunov** [comment]
В everware можно зайти в Control Panel - нажать fork, потом push, проверить, что в ваш репозиторий запушены все сделанные вами изменения. Затем в everware сделать stop, а когда он завершится, вставить ссылку на ваш репозиторий.
